# uuid: 27737844-4dfb-469e-9bee-3a2be73b8117
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.initiative
  module:
    - text
id: node.initiative.body
field_name: body
entity_type: node
bundle: initiative
label: Body
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: true
field_type: text_with_summary

